<?php

declare(strict_types=1);

namespace Syscage\Plugin;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Routing\Router;
use Syscage\Plugin\Contracts\FrontendManifestGeneratorInterface;
use Syscage\Plugin\Contracts\PluginInterface;
use Syscage\Plugin\Support\PluginRouteFinder;

/**
 * Default implementation of {@see FrontendManifestGeneratorInterface}.
 */
final class FrontendManifestGenerator implements FrontendManifestGeneratorInterface
{
    private const PAGE_EXTENSIONS = ['tsx', 'ts', 'jsx', 'vue'];

    public function __construct(
        private readonly Filesystem $files,
        private readonly Router $router,
        private readonly PluginRouteFinder $routes,
        private readonly string $cachePath,
    ) {
    }

    public function generate(array $plugins): string
    {
        $pages = [];
        $routes = [];
        $sidebar = [];

        foreach ($plugins as $plugin) {
            $pages = array_merge($pages, $this->pagesFor($plugin));
            $routes = array_merge($routes, $this->routesFor($plugin));

            if ($plugin->sidebar() !== []) {
                $sidebar[$plugin->alias()] = $plugin->sidebar();
            }
        }

        $contents = $this->render($pages, $routes, $sidebar);

        $directory = dirname($this->cachePath);

        if (! $this->files->isDirectory($directory)) {
            $this->files->makeDirectory($directory, recursive: true);
        }

        $this->files->put($this->cachePath, $contents);

        return $contents;
    }

    /**
     * @return array<string, string>
     */
    private function pagesFor(PluginInterface $plugin): array
    {
        $pagesDirectory = $plugin->resourcePath('js' . DIRECTORY_SEPARATOR . 'Pages');

        if (! $this->files->isDirectory($pagesDirectory)) {
            return [];
        }

        $pages = [];

        foreach ($this->files->allFiles($pagesDirectory) as $file) {
            if (! in_array($file->getExtension(), self::PAGE_EXTENSIONS, true)) {
                continue;
            }

            $relative = str_replace('\\', '/', $file->getRelativePathname());
            $withoutExtension = preg_replace('/\.' . preg_quote($file->getExtension(), '/') . '$/', '', $relative);

            $pageKey = $plugin->alias() . '/' . $withoutExtension;
            $importPath = $this->relativePath(dirname($this->cachePath), $file->getPathname());

            $pages[$pageKey] = $importPath;
        }

        return $pages;
    }

    /**
     * @return array<int, array{method: string, uri: string, name: ?string}>
     */
    private function routesFor(PluginInterface $plugin): array
    {
        return array_map(
            static fn ($route): array => [
                'method' => implode('|', $route->methods()),
                'uri' => $route->uri(),
                'name' => $route->getName(),
            ],
            $this->routes->forPlugin($this->router, $plugin),
        );
    }

    /**
     * @param array<string, string> $pages
     * @param array<int, array{method: string, uri: string, name: ?string}> $routes
     * @param array<string, array<string, mixed>> $sidebar
     */
    private function render(array $pages, array $routes, array $sidebar): string
    {
        $pageEntries = [];

        foreach ($pages as $key => $importPath) {
            $pageEntries[] = sprintf(
                '  %s: () => import(%s),',
                json_encode($key, JSON_UNESCAPED_SLASHES),
                json_encode($importPath, JSON_UNESCAPED_SLASHES),
            );
        }

        $pagesBlock = $pageEntries === [] ? '' : "\n" . implode("\n", $pageEntries) . "\n";
        $routesJson = json_encode($routes, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $sidebarJson = json_encode((object) $sidebar, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        return <<<TS
        // This file is generated by the Syscage Plugin Framework.
        // Do not edit it directly — run `php artisan plugin:cache` to rebuild it.

        export interface PluginRoute {
          method: string;
          uri: string;
          name: string | null;
        }

        export const pluginPages: Record<string, () => Promise<unknown>> = {{$pagesBlock}};

        export const pluginRoutes: PluginRoute[] = {$routesJson};

        export const pluginSidebar: Record<string, unknown> = {$sidebarJson};

        TS;
    }

    private function relativePath(string $from, string $to): string
    {
        $from = str_replace('\\', '/', rtrim($from, '/\\'));
        $to = str_replace('\\', '/', $to);

        $fromParts = explode('/', $from);
        $toParts = explode('/', $to);

        while ($fromParts !== [] && $toParts !== [] && $fromParts[0] === $toParts[0]) {
            array_shift($fromParts);
            array_shift($toParts);
        }

        $relative = str_repeat('../', count($fromParts)) . implode('/', $toParts);

        return str_starts_with($relative, '.') ? $relative : './' . $relative;
    }
}
